### Are sessions recorded?

We encourage you to attend our live sessions in real-time as they are designed to be interactive, but if you cannot attend any session, we will also make recordings available for you as well. Simply click on the calendar link on the left to access these recordings.

### What are the live sessions?

There are several live sessions per week:

**Lecture**: during this session, your instructor will highlight the most important material from the pre-reading and lay the foundation for what you will need to know to be able to complete the weekly project. Sometimes guest lecturers attend these sessions as well.

**Project Session**: this highly interactive session is focused on supporting you as you get started on the weekly project. The instructor will review the project and then you and your classmates will break into groups and start working on it.

**Office Hours**: these sessions are an opportunity for you to get questions related to the course material or the weekly projects answered. Everyone who attends Office Hours works on their project independently, and asks classmates and TAs questions as they get stuck. These sessions are optional, but students love them and highlight their utility.

### What is the time commitment for this course?

Our courses are designed for busy, working adults; we know this isn't the only thing you are doing! The course requires 5-7 hours/week of work. The majority of this time will be spent building on your projects, which you can do independently whenever fits best in your schedule.

### Are there course deadlines or do I go at my own pace?

Each week you will be assigned a project that mirrors real-world work in the course area. You will submit your project at the end of the week, and you will review projects submitted by your peers. Outside of the live sessions, you can choose how to complete readings and work on your project.

### Will I be given a certificate at the end of the course?

We hope so! Everyone who completes 2 out of the 2 course projects, and demonstrates proficiency with the material, will be given a certificate of completion.

### Will I have access to the class when the class is over?

Only students who have an active CoRise Membership will continue to have access to the course material when the cohort ends. Regular course enrollments will lose access 30 days after the end of the course.
