### How to Prepare for This Course?

We created CoRise for professionals looking to acquire new skills. This course is a "flipped classroom" model, and it moves quickly. To make the most of your CoRise experience, we recommend three key tips:

#### **Look ahead before the week**

Tactically anticipate that CoRise will require a commitment of time and energy. Block out 6-8 hours each week on your calendar during your course.

Review the course materials and project before the week starts. The live sessions are meant to complement the material and project; this is NOT the type of course where you can show up to live sessions and learn everything you need to complete the projects. Take at least an hour to read the course material before the Monday lecture and review the project before the project session.

#### **Ask questions when you are stuck**

We have a "no dumb questions" philosophy at CoRise. Reach out if you are having an issue and ask a question in Slack! Others will benefit from learning alongside you 😁.

#### **Do as much of the weekly project as possible and submit what you have**

We have designed this course to be at the intersection of challenge and ability, which means some of the material will be difficult! Don't worry if you're having trouble completing the weekly project. Just do as much as you can, and submit what you have. We primarily care that you are learning and building your skill set, not that your weekly project is completely polished. When you submit your project, you can indicate where you got stuck or where you need assistance, and your peer reviewer will assist you.

Your experience going through course materials will depend on your familiarity with the content and your learning style, but below is a potential guide to help manage your time.

There are two core sessions we expect everyone to attend:

+---------------------------+---------------------------------------------------------------------------+
| Session                   | You will leave this session with:                                         |
+===========================+===========================================================================+
| Monday Lecture            | An understanding of the week's content                                    |
+---------------------------+---------------------------------------------------------------------------+
| Wednesday Project Kickoff | The weekly project explained and the first part of the project completed. |
+---------------------------+---------------------------------------------------------------------------+
|                           |                                                                           |
+---------------------------+---------------------------------------------------------------------------+

There are additional, non-mandatory, sessions to attend as needed:

+----------------------------+--------------------------------------------------------------------+
| **Session**                | You will leave this session with:                                  |
+============================+====================================================================+
| Tuesday Catch-up Hour      | The previous week's project completed                              |
|                            |                                                                    |
| (Beginning in Week 2)      |                                                                    |
+----------------------------+--------------------------------------------------------------------+
| Friday Office Hours        | Open-ended questions about the week's project and content answered |
+----------------------------+--------------------------------------------------------------------+
| Sunday Project Walkthrough | A walkthrough from start to finish of the week's project           |
+----------------------------+--------------------------------------------------------------------+
|                            |                                                                    |
+----------------------------+--------------------------------------------------------------------+

[SIDEBAR]

Time Management

-   **Monday:** 1-hour live lecture

-   **Monday-Wednesday**: Go through the articles and coding exercises, completing as many as you can and asking any questions in Slack. You will likely need to allocate about an hour each day, or more if you're new to programming.

-   **Wednesday**: 1-hour project kickoff; start going through the project with course team and classmates.

-   **Friday**: Office hours: Once a week, your TA will host a session for you to work on your weekly project with the support of peers and the TA if needed.

-   **Sunday**: Project Walkthrough: Once a week, your TA will walk through the weekly project from start to finish to ensure you have what you need to succeed on the project.

-   **Sunday Evening**: Submit your project

-   **Monday Evening:** Complete your code/peer review. You can review other project submissions in the #projects Slack channel for inspiration and learning.

[SIDEBAR]
