---
title: "Project 1: Exploring 100+ Years of US Baby Names"
output: 
  flexdashboard::flex_dashboard:
    storyboard: true
    social: menu
    source: embed
---

```{r setup, include = FALSE}
library(tidyverse)
library(flexdashboard)
FILE_NAME <- here::here("data/names.csv.gz")
tbl_names <- readr::read_csv(FILE_NAME, show_col_types = FALSE)
knitr::opts_chunk$set(
  fig.path = "img/",
  fig.retina = 2,
  fig.width = 6,
  fig.asp = 9/16,
  fig.pos = "t",
  fig.align = "center",
  # dpi = if (knitr::is_latex_output()) 72 else 150,
  out.width = "100%",
  # dev = "svg",
  dev.args = list(png = list(type = "cairo-png")),
  optipng = "-o1 -quiet"
)
ggplot2::theme_set(ggplot2::theme_gray(base_size = 8))
```

### Header 1

```{r results = "hide"}
# PASTE BELOW >> CODE FROM question-1-transform

```


```{r}
# PASTE BELOW >> CODE FROM question-1-plot BELOW

```

***

<!-- Add a note to be included in the sidebar -->


### Header 2

```{r results = "hide"}
# PASTE BELOW >> CODE FROM question-2-transform 

```


```{r}
# PASTE BELOW >> CODE FROM question-2-visualize

```

***

<!-- Add a note to be included in the sidebar -->

### Header 3

```{r results = "hide"}
# PASTE BELOW >> CODE FROM question-3-transform-1 and question-3-transform-2

```


```{r}
# PASTE BELOW >> CODE FROM question-3-visualize-1

```

***

<!-- Add a note to be included in the sidebar -->

